// Generated from ../migrations/*.sql (the D1 schema wrangler applies) for the
// standalone binary's migration runner; do not edit.
export interface Migration {
  name: string;
  sql: string;
}

export const migrations: readonly Migration[] = [
  {
    "name": "0001_init.sql",
    "sql": "-- Ola Ink D1 schema.\n--\n-- Table and column names intentionally match the pre-migration SQLite schema\n-- so the Phase 3 data migration is a straight row copy. Two deliberate\n-- differences:\n--   * prototype_notes no longer stores record_json (the payload moved to R2,\n--     one object per note record ID);\n--   * prototype_server_state was retired (its only consumer was a one-time\n--     echo-key cleanup, already run on the production database);\n--   * pairing_claim_buckets is new: free-plan rate limiting for\n--     POST /v1/pairings/claim (one 60s counter bucket per client key).\n\nCREATE TABLE prototype_directories (\n  user_id TEXT PRIMARY KEY,\n  version INTEGER NOT NULL CHECK (version >= 0)\n);\n\nCREATE TABLE prototype_devices (\n  device_id TEXT PRIMARY KEY,\n  user_id TEXT NOT NULL REFERENCES prototype_directories(user_id) ON DELETE CASCADE,\n  public_key_spki TEXT NOT NULL,\n  created_at INTEGER NOT NULL\n);\nCREATE INDEX prototype_devices_by_user ON prototype_devices(user_id, device_id);\n\nCREATE TABLE prototype_notes (\n  id TEXT PRIMARY KEY,\n  created_at INTEGER NOT NULL\n);\n\nCREATE TABLE prototype_note_deliveries (\n  device_id TEXT NOT NULL REFERENCES prototype_devices(device_id) ON DELETE CASCADE,\n  record_id TEXT NOT NULL REFERENCES prototype_notes(id) ON DELETE CASCADE,\n  PRIMARY KEY (device_id, record_id)\n);\nCREATE INDEX prototype_note_deliveries_by_device ON prototype_note_deliveries(device_id, record_id);\n\nCREATE TABLE prototype_accounts (\n  subject TEXT PRIMARY KEY,\n  user_id TEXT NOT NULL UNIQUE,\n  created_at INTEGER NOT NULL\n);\n\n-- The no-username-reuse promise rests on canonical_username staying UNIQUE\n-- across active assignments and retired tombstones. Never enable\n-- multi-region D1 without redesigning this table.\nCREATE TABLE account_usernames (\n  canonical_username TEXT PRIMARY KEY,\n  user_id TEXT NOT NULL UNIQUE,\n  status TEXT NOT NULL CHECK (status IN ('active', 'retired')),\n  assigned_at INTEGER NOT NULL,\n  retired_at INTEGER\n);\n\nCREATE TABLE prototype_pairings (\n  code TEXT PRIMARY KEY,\n  user_id TEXT NOT NULL REFERENCES prototype_directories(user_id) ON DELETE CASCADE,\n  expires_at INTEGER NOT NULL\n);\nCREATE INDEX prototype_pairings_expiry ON prototype_pairings(expires_at);\n\n-- A pairing-created capability is restricted to one already-enrolled\n-- companion device's poll/ack operations. Only its SHA-256 digest is\n-- durable; the raw bearer value exists only in the companion profile.\nCREATE TABLE prototype_device_sessions (\n  token_hash TEXT PRIMARY KEY,\n  device_id TEXT NOT NULL REFERENCES prototype_devices(device_id) ON DELETE CASCADE,\n  created_at INTEGER NOT NULL\n);\nCREATE INDEX prototype_device_sessions_by_device ON prototype_device_sessions(device_id);\n\nCREATE TABLE pairing_claim_buckets (\n  client_key TEXT NOT NULL,\n  window_start INTEGER NOT NULL,\n  count INTEGER NOT NULL DEFAULT 1,\n  PRIMARY KEY (client_key, window_start)\n);\n"
  }
];
